Added validity check in number input
qbcore-framework/qb-input pull request #30
Opened 2022-11-04 23:36 UTC by arsh939

**Describe Pull request**
Added validity check and minimum value in number input which prevents the pointer bug. It prevents the player to use a float amount in the input field.

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes] (Be honest)
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]

2022-11-05 04:04 UTC, singh-manavv approved these changes

2022-11-05 06:54 UTC, HarshZode approved these changes

2022-11-05 19:31 UTC, kinglion014 approved these changes

2022-12-08 06:08 UTC, Z3rio approved these changes
Looks fine to me.

2022-12-12 17:32 UTC, Z3rio requested changes
Although the code looks fine, I dont believe this validity check would be great for every single input.
I will commit it if you add a toggle of some sort to it, so it doesnt get aded onto all inputs even if you dont want it.

2023-11-01 23:34 UTC, closed without merging