fixed issue with commit #8
qbcore-framework/qb-input pull request #9
Opened 2021-12-24 05:45 UTC by WaydeTheKiwi

Added class ids to all input options and divs etc for custom CSS
If Null, sets to default
formID
formClass
footerClass
headerClass
submitClass
inputClass
divGroupClass
divGroupTitleClass
divInputGroupClass
divSelectTitle
divformSelect

2021-12-31 07:32 UTC, ItsAegeus commented
Can confirm it fixed the problems.

2021-12-31 12:44 UTC, WaydeTheKiwi commented
It did for me, go test it

On Fri., Dec. 31, 2021, 12:33 a.m. Louis, ***@***.***> wrote:

> Can confirm it fixed the problems.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/qbcore-framework/qb-input/pull/9#issuecomment-1003296299>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACNX33NEBGK6HUJQ2B6VMCLUTVMC5ANCNFSM5KWCAEJQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-01-01 10:41 UTC, IdrisDose requested changes
I've written comments on the code where there will be problems.

2022-01-01 10:41 UTC, IdrisDose commented on html/script.js
> +const formID = "";
Should be changed to `let formID = "";`

2022-01-01 10:41 UTC, IdrisDose commented on html/script.js
>  	const formID = data.formID != null ? data.formID : "qb-input-form";
remove `const` keyword and change to `formID = data.formID != null ? data.formID : "qb-input-form";`

2022-01-01 10:41 UTC, IdrisDose commented on html/script.js
> +    $(formID).on("change", function (event) {
Will create issues;

try changing to $(\`#${formID}\`).on("change"

2022-01-01 10:41 UTC, IdrisDose commented on html/script.js
> +    $("#" + formID).on("submit", async function (event) {
please try and stick to string literal rather than string concats:
$(\`#${formID}\`)

2022-01-01 10:41 UTC, IdrisDose commented on html/script.js
> +        let formData = $("#" + formID).serializeArray();
please try and stick to string literal rather than string concats:
$(\`#${formID}\`)

2022-01-01 10:41 UTC, IdrisDose commented on html/script.js
> +    $(formID).remove();
Will also not run since wrong target.
$(\`#${formID}\`)

2022-01-02 02:36 UTC, closed without merging